### ISSUE TITLE
Undefined constant "X\DS"

### ISSUE THREAD

**Issue by MaluNoPeleke** [genxbe/kirby3-instagram#10]
After upgrading to Kirby 4 I have a problem with the Kirby3-Instagram Plugin by @genxbe:

```
Error: Undefined constant "X\DS" in /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:17
Stack trace:
#0 /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/fetch.php(27): X\Instagram->__construct()
#1 {main}
Error: Undefined constant "X\DS" in file /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php on line 17
Stack trace:
  1. Error->() /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:17
  2. X\Instagram->__construct() /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/fetch.php:27
```
![image](https://github.com/genxbe/kirby3-instagram/assets/1446541/dc08cf2a-88ad-48af-9a5c-d388725ca24e)

How to solve it?

**Comment by MaluNoPeleke** [comment]
Fix: https://github.com/genxbe/kirby3-instagram/pull/11
Thanks to @textnixe

**Comment by MaluNoPeleke** [comment]
Follow up error

Whoops\Exception\ErrorException: Undefined array key "media" in /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:149
Stack trace:
#0 /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php(149): Whoops\Run->handleError(2, 'Undefined array...', '/var/www/virtua...', 149)
#1 /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/fetch.php(27): X\Instagram->fetch()
#2 {main}
Whoops\Exception\ErrorException: Undefined array key "media" in file /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php on line 149
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:149
  2. Whoops\Run->handleError() /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:149
  3. X\Instagram->fetch() /var/www/virtual/peleke7/peleke.de/site/plugins/kirby3-instagram/fetch.php:27

**Comment by andykamezou** [comment]
> Fix: #11 Thanks to @textnixe

Your fix works.
But you need to check line 140 & 153. I guess you tried to replace all "DS", so "fields" become "fielDIRECTORY_SEPARATOR" which might cause the follow-up error that you get.

**Comment by MaluNoPeleke** [comment]
Thanks, I fixed that in the last commit.
